require("config/gbbaby")

require("config/autopairs")
require("config/autotag")
require("config/gitsigns")
require("config/bufferline")
require("config/lualine")
require("config/lsp")
require("config/dashboard")
require("config/nvim_icons")
require("config/telescope")
require('config/colorizer')
require('config/blankline')
require('config/cmp')
require('config/nvimtree')
require('config/treesitter')
require('config/emmet')
require('config/luasnip')
