local jet_config = require("jet.JetConfig")
-- require("jet.config.plugins.gbbaby")
require("jet.config.plugins.jetly")
require("jet.config.plugins.autopairs")
require("jet.config.plugins.autotag")
require("jet.config.plugins.gitsigns")
require("jet.config.plugins.bufferline")
require("jet.config.plugins.lualine")
require("jet.config.plugins.lsp")
require("jet.config.plugins.dashboard")
require("jet.config.plugins.nvim_icons")
require("jet.config.plugins.telescope")
require('jet.config.plugins.colorizer')
require('jet.config.plugins.blankline')
require('jet.config.plugins.cmp')
if jet_config.plugins.NvimTree then
  require('jet.config.plugins.nvimtree')
end
require('jet.config.plugins.treesitter')
require('jet.config.plugins.emmet')
require('jet.config.plugins.luasnip')
