local jet_config = require("jetConfig")
require("config.plugins.gbbaby")
-- require("config.plugins.jetly")
require("config.plugins.autopairs")
require("config.plugins.autotag")
require("config.plugins.gitsigns")
require("config.plugins.bufferline")
require("config.plugins.lualine")
require("config.plugins.lsp")
require("config.plugins.dashboard")
require("config.plugins.nvim_icons")
require("config.plugins.telescope")
require('config.plugins.colorizer')
require('config.plugins.blankline')
require('config.plugins.cmp')
if jet_config.plugins.NvimTree then
  require('config.plugins.nvimtree')
end
require('config.plugins.treesitter')
require('config.plugins.emmet')
require('config.plugins.luasnip')
